- name: Deploy Campus Application
  hosts: localhost
  connection: local
  become: false

  vars:
    backend_image: "siddhhhhh/campus-backend:latest"
    frontend_image: "siddhhhhh/campus-frontend:latest"
    mongo_uri: "mongodb+srv://mahig1705:Mahi%401705@cluster0.nfeadj3.mongodb.net/campus?retryWrites=true&w=majority"

  tasks:
    - name: Pull latest backend image
      shell: docker pull {{ backend_image }}

    - name: Pull latest frontend image
      shell: docker pull {{ frontend_image }}

    # 🔥 FIXED (no conflict ever)
    - name: Remove old backend container
      shell: docker rm -f backend || true

    - name: Run backend container
      shell: |
        docker run -d -p 5000:5000 \
          --name backend \
          --restart unless-stopped \
          -e MONGO_URI="{{ mongo_uri }}" \
          {{ backend_image }}

    - name: Remove old frontend container
      shell: docker rm -f frontend || true

    - name: Run frontend container
      shell: |
        docker run -d -p 3000:80 \
          --name frontend \
          --restart unless-stopped \
          {{ frontend_image }}

    - name: Verify containers
      shell: docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      register: container_status

    - name: Print container status
      debug:
        msg: "{{ container_status.stdout }}"